<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Features\**" />
    <Compile Remove="Mappings\**" />
    <Compile Remove="Services\**" />
    <Compile Remove="Validators\**" />
    <EmbeddedResource Remove="Features\**" />
    <EmbeddedResource Remove="Mappings\**" />
    <EmbeddedResource Remove="Services\**" />
    <EmbeddedResource Remove="Validators\**" />
    <None Remove="Features\**" />
    <None Remove="Mappings\**" />
    <None Remove="Services\**" />
    <None Remove="Validators\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="16.1.1" />
    <PackageReference Include="FluentValidation" Version="12.1.1" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ProdFalcon.Domain\ProdFalcon.Domain.csproj" />
    <ProjectReference Include="..\ProdFalcon.Shared\ProdFalcon.Shared.csproj" />
  </ItemGroup>

</Project>
