<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Configurations\**" />
    <Compile Remove="Extensions\**" />
    <Compile Remove="Middlewares\**" />
    <Content Remove="Configurations\**" />
    <Content Remove="Extensions\**" />
    <Content Remove="Middlewares\**" />
    <EmbeddedResource Remove="Configurations\**" />
    <EmbeddedResource Remove="Extensions\**" />
    <EmbeddedResource Remove="Middlewares\**" />
    <None Remove="Configurations\**" />
    <None Remove="Extensions\**" />
    <None Remove="Middlewares\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.26">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="8.0.26" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="8.0.26">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Scalar.AspNetCore" Version="2.14.14" />
    <PackageReference Include="Serilog.AspNetCore" Version="8.0.3" />
    <PackageReference Include="Serilog.Settings.Configuration" Version="8.0.4" />
    <PackageReference Include="Serilog.Sinks.Console" Version="6.0.0" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="10.1.7" />
    <PackageReference Include="System.IO.Compression.ZipFile" Version="4.3.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ProdFalcon.Application\ProdFalcon.Application.csproj" />
    <ProjectReference Include="..\ProdFalcon.Infrastructure\ProdFalcon.Infrastructure.csproj" />
    <ProjectReference Include="..\ProdFalcon.Shared\ProdFalcon.Shared.csproj" />
  </ItemGroup>

</Project>
