<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ProdFalcon.Application\ProdFalcon.Application.csproj" />
    <ProjectReference Include="..\ProdFalcon.Infrastructure\ProdFalcon.Infrastructure.csproj" />
    <ProjectReference Include="..\ProdFalcon.Shared\ProdFalcon.Shared.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Controllers\" />
  </ItemGroup>

</Project>
