<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.26">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="8.0.26" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="8.0.26">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Scalar.AspNetCore" Version="2.14.14" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="10.1.7" />
    <PackageReference Include="System.IO.Compression.ZipFile" Version="4.3.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ProdFalcon.Application\ProdFalcon.Application.csproj" />
    <ProjectReference Include="..\ProdFalcon.Infrastructure\ProdFalcon.Infrastructure.csproj" />
    <ProjectReference Include="..\ProdFalcon.Shared\ProdFalcon.Shared.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Middlewares\" />
    <Folder Include="Extensions\" />
    <Folder Include="Configurations\" />
  </ItemGroup>

</Project>
